---
title: Promise
date: 2022-10-04 17:37:56
excerpt: "This is excerpt of the scries"
cover_image: /images/posts/img1.jpeg
tag: [JavaScript]
draft: true
---

# Promise

Promise 상태

- 대기(pending)
- 이행(fulfilled)
- 거부(rejected)

Promise 생성

```JavaScript
let promise = new Promise(function(resolve, reject) {
  // executor
})
```

프로미스는 콜백함수를 변수로 받는데 이를 executor라고 한다.
executor는 변수로 resolve와 reject를 사용하는데, 이는 프로미스에서 알아서 처리해주므로 별도로 만들 필요는 없다.
executor는 프로미스를 만드는 즉시 실행되는데, 안에서 resolve나 reject를 반드시 호출해야 한다.

- resolve(value): 일이 성공적으로 끝난경우 value와 함께 호출
- reject(error): 에러 발생시 error 호출

프로미스 내부 프로퍼티는 value, state가 있는데 resolve나 reject의 실행에 따라 아래처럼 변한다.

```JavaScript
{
  state: pending,
  result: undefined
}
-> resolve(value) ->
{
  state: fulfilled,
  result: value
}

{
  state: pending,
  result: undefined
}
-> reject(error) ->
{
  state: rejected,
  result: error
}
```

## then

```JavaScript
promise.then(
  function(value) {/* resolve handling*/},
  function(error) {/* reject handling*/}
)
```

then의 첫 번째 변수는 프로미스가 이행 되었을 때 실행되는 함수로, resolve 시의 value 값을 사용한다.
then의 두 번째 변수는 프로미스가 거부 되었을 때 실행되는 함수로, reject의 error를 사용한다.

```JavaScript
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => {
    resolve("resolved")
  }, 1000);
});

promise.then(
  result => alert(result), // 1초 후에 resolved 출력
  error => alert(error) // 실행되지 않음
)
```

```JavaScript
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => {
    rejecte(new Error("error occured"))
  }, 1000);
});

promise.then(
  result => alert(result), // 실행되지 않음
  error => alert(error) // 1초 후에 에러 출력
)
```

성공한 경우만 다루고 싶으면 첫 번째 변수만 적어준다.

## catch

에러가 발생한 경우만 다루고 싶으면 `.then(null, errorHandling)`을 사용하거나 catch를 사용한다.

```JavaScript
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => {
    rejecte(new Error("error occured"))
  }, 1000);
});

promise.catch(
  error => alert(error) // 1초 후에 에러 출력
)
```

## finally

프로미스가 실행된 이후에 항상 실행시키고 싶은 함수는 finally에 추가할 수 있다.

```JavaScript
new Promise((resolve, reject) => {
  /* do asynchronous works */
})
  .finally(() => {
    alert("Promise is ready")
  })
  .then((result) => alert(result), (error) => alert(error));
```

finally는 프로미스가 이행되었는지, 거부되었는지 알 수 없다.

## Promise Chaining

`promise.then`은 프로미스를 반환한다.
그러므로 반환된 프로미스에도 then을 사용할 수 있고, 이를 반복하면 비동기 함수를 순차적으로 실행시킬 수 있다.

```JavaScript
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => {
    resolve(1)
  }, 1000);
}).then(function(result) {
  result => alert(result);
  return result * 2;
}).then(function (result) {
  result => alert(result);
  return result * 2;
}).then(function (result) {
  result => alert(result);
  return result * 2;
})
```

위 같은 일이 가능한 이유는 then의 반환값이 프로미스의 값으로 사용되기 때문이다.
그래서 반환값이 프로미스 내부로 전달되고, 이 값을 다음 then에서 쓸 수 있게 된다.
여기서 값을 반환하는 것이 아니라 프로미스를 반환해도 되는데, 이 경우 반환된 프로미스를 사용한다.

```JavaScript
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => {
    resolve(1)
  }, 1000);
}).then(function(result) {
  result => alert(result);
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(result * 2), 1000);
  });
}).then(function (result) {
  result => alert(result);
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(result * 2), 1000);
  });
}).then(function (result) {
  result => alert(result);
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(result * 2), 1000);
  });
})
```

## Error handling

프로미스가 거부되면 가장 가까운 rejection 핸들러로 넘어간다.
간단히 말해 가장 가까운 catch나 then의 두 번째 변수를 실행시킨다.

```JavaScript
fetch('https://no-such-server.blabla') // 거부
  .then(response => response.json())
  .catch(err => alert(err)) // TypeError: failed to fetch (출력되는 내용은 다를 수 있음)
```

## Promise.all

## Promise.race

## async/await

function 앞에 async를 붙이면 해당 함수는 항상 프로미스를 반환한다.
이때 함수가 프로미스를 반환하지 않더라도, 결과값에 resolve 함수로 감싸서 전달해준다.
예를 들어 아래 코드는 1을 결과값으로 하는 프로미스가 반환된다.

```JavaScript
async function f() {
  return 1;
}

f().then(alert); // 1
```

자바스크립트는 await을 만나면 프로미스가 처리될때가지 기다린다.

```JavaScript
async function f() {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("finished", 1000))
  });

  let result = await promise;   // (*)

  alert(result);
}

f();
```

함수를 호출하면 (\*)에서 잠시 중단 되었다가, 프로미스가 완료되면 다음 코드가 실행된다.
이때 await과 같이 사용된 프로미스가 반환한 값은 프로미스 프로퍼티의 result 값이 된다.
await은 async 함수 내에서만 사용할 수 있다.
async/await을 사용할 때의 장점은 then이 이어지는 코드를 await으로 간결하게 해결할 수 있다는 것이다.

await을 사용하다가 에러가 발생하는 경우는 try/catch를 사용해서 해결할 수 있다.

```JavaScript
async function f() {

  try {
    let response = await fetch('http://유효하지-않은-주소');
  } catch(err) {
    alert(err); // TypeError: failed to fetch
  }
}

f();
```

또는 반환되는 async 함수의 반환이 프로미스이므로 catch를 사용해 아래처럼 작성할 수 있다.

```JavaScript
async function f() {
    let response = await fetch('http://유효하지-않은-주소');
}

f().catch(alert);
```

# Reference

1. [Javascript.info](https://ko.javascript.info/async)
